before_script:
tests:
    stage: test
    script:
        - virtualenv env
        - source env/bin/activate
        - pip install -U pip wheel setuptools
        - XDG_CACHE_HOME=/cache pip3 install -r src/requirements.txt --no-use-pep517 -Ur src/requirements/dev.txt
        - cd src
        - python manage.py check
        - make all compress
        - py.test --reruns 3 -n 3 tests
    tags:
        - python3
    except:
        - pypi
pypi:
    stage: release
    script:
        - cp /keys/.pypirc ~/.pypirc
        - virtualenv env
        - source env/bin/activate
        - pip install -U pip wheel setuptools check-manifest twine
        - XDG_CACHE_HOME=/cache pip3 install -Ur src/requirements.txt -r src/requirements/dev.txt
        - cd src
        - python setup.py sdist
        - pip install dist/pretix-*.tar.gz
        - python -m pretix migrate
        - python -m pretix check
        - check-manifest
        - python setup.py sdist bdist_wheel
        - twine check dist/*
        - twine upload dist/*
    tags:
        - python3
    only:
        - pypi
    artifacts:
        paths:
            - src/dist/
stages:
    - test
    - build
    - release
